menu:
    Blog: /
    Archive: /archives/
    Weibo: http://weibo.com/iamsosorry
    GitHub: https://github.com/tttpeng
    About: /about/about.html
    
favicon: /favicon.png
logo: /favicon.png

# Comment
# e.g disqus: seansun
disqus:
duoshuo:

# Analytics
# google-analytics:
ga: UA-65933410-1

# Copyright Infomation
startyear: 2015
